### ISSUE TITLE
Cannot Compile The Pose Regressor

### ISSUE THREAD

**Issue by Hiperdyne19012** [chensong1995/HybridPose#10]
I have been trying to compile the Pose Regressor but I'm getting errors like "error: ‘Eigen::Vector4d’ has no member named ‘head’." I have made sure to use eigen3 in the include of the Makefile ( -I /usr/include/eigen3). But I'm still getting these errors with Eigen.

**Comment by chensong1995** [comment]
Hello Hiperdyne19012,

Thanks for trying out our code!

You do not have to make any modifications to the Makefile. Please try cloning our repository using `git clone --recurse-submodules git@github.com:chensong1995/HybridPose.git`. The `--recurse-submodules` option automatically downloads Eigen to the directory recognizable by the Makefile.

Let me know if this solves the problem.

**Comment by Hiperdyne19012** [comment]
> Hello Hiperdyne19012,
> 
> Thanks for trying out our code!
> 
> You do not have to make any modifications to the Makefile. Please try cloning our repository using `git clone --recurse-submodules git@github.com:chensong1995/HybridPose.git`. The `--recurse-submodules` option automatically downloads Eigen to the directory recognizable by the Makefile.
> 
> Let me know if this solves the problem.

Thanks it worked. I had configure the SSH Keys (https://stackoverflow.com/questions/2643502/how-to-solve-permission-denied-publickey-error-when-using-git).
