### ISSUE TITLE
Some problems about the number of images used

### ISSUE THREAD

**Issue by JJJano** [chensong1995/HybridPose#11]
Thank you for your valuable research and code. 

Do you only use the original Linemod image in your paper? Is offline rendering or online data augmentation used? If so, where can I find the code for rendering or data augmentation

**Comment by chensong1995** [comment]
Hello JJJano, 

Thanks for your interest in our work!

No, we do not use any synthesized training example.

**Comment by JJJano** [comment]
Thank you for your reply.
