### ISSUE TITLE
About prediction_file in evaluate.py

### ISSUE THREAD

**Issue by firstdeep** [chensong1995/HybridPose#16]
Thank you for sharing your excellent research.

I'm going to run train 1 and then test 1.
However, the ADD value cannot be output because there is no prediction_file to proceed with the test.

So I want you to tell me **how to save and get prediction_file file.** 
https://github.com/chensong1995/HybridPose/blob/master/src/evaluate.py#L12

https://github.com/chensong1995/HybridPose/blob/master/src/evaluate.py#L65

Thank you very much.

Regards,
David.

**Comment by chensong1995** [comment]
Hello David,

Thank you for your interest in our research!

Please refer to [this line](https://github.com/chensong1995/HybridPose/blob/master/trainers/coretrainer.py#L629) for the prediction file. If you run `train_core.py` with [our released pre-trained weights ](https://github.com/chensong1995/HybridPose/blob/master/src/train_core.py#L30), the file will be automatically generated.

I hope this helps.
