### ISSUE TITLE
Question on how to run inference

### ISSUE THREAD

**Issue by neixlo** [chensong1995/HybridPose#23]
Hello @chensong1995 ,
thanks for your research, making this code available and answering all those questions from the community!

I can't figure out how to run (just) inference on HybridPose.

The prediction part is not the problem. 
I've downloaded the pretrained weights, modified the `forward() `so I can compute
`sym_cor_pred, mask_pred, pts2d_map_pred, graph_pred = model(img)`
 

I struggle with the regression module.
R_pred, t_pred, R_init, t_init = self.regress_pose(...)

I think I can:
- pass regressor and predictions
- pass camera_intrinsic to calculate K_inv.
- pass the estimated pred matrixes of the prediction network.

Questions: 

1. Is the calculation of `pr_para` and `pi_para` just necessary one time? So I could save them and pass a constant when running inference.

2. What is `batch['pts3d'][i]` and `batch['normal'][i]` doing in regress_pose()? They are from the dataset and should not matter during inference. But I can't follow your code along and don't know what to pass.

Thanks in advance!

**Comment by chensong1995** [comment]
Hello neixlo,

Thanks for your interest in our project!

1. You do not have to compute `pr_para` or `pi_para` every iteration "on the fly". You can save them somewhere and load them when needed.
2. `batch['pts3d'][i]` is the 3D keypoints represented in the object coordinate system. `batch['normal'][i]` is the normal of the 3D symmetry plane represented in the object coordinate system. They are the same across different images containing the same object. Pose regression is formulated as an optimization problem: it tries to find the rigid pose `(R, t)`, which, if applied to the 3D intermediate representations (keypoints, symmetry plane, edge vectors) in the object coordinate system, will best align with the predicted 2D intermediate representations on the image plane. You are right that at inference time, we are not supposed to use any ground-truth information on the image plane or in the camera coordinate system. However, both `batch['pts3d'][i]` and `batch['normal'][i]` are in the object coordinate system.

I hope this helps!

**Comment by neixlo** [comment]
I understand, thanks for this explanation!

**Comment by neixlo** [comment]
Hi @chensong1995 ,
I've got one more question:
Am I right that the `pr_para` and `pi_para` parameters as they appear in the python script are something like pointers which get passed to the c++ wrapper?

When I print and save them, they are just integers which seem to cause a segmentation fault (core dumped) when running 
```
predictions = regressor.initialize_pose(predictions, 
                                            pi_para, 
                                            self.args.use_keypoint, 
                                            self.args.use_edge, 
                                            self.args.use_symmetry
predictions = regressor.refine_pose(predictions, pr_para,
                                            self.args.use_keypoint, 
                                            self.args.use_edge, 
                                            self.args.use_symmetry)
```

```
pr_para = 94526787016960
pi_para = 94526787039232
```

Thanks for your time!

**Comment by chensong1995** [comment]
You're right. They are pointers to C++ objects. Please take a look at repressor.py and wrapper.cpp if you want to interact with these pointers. 

I hope it helps.
