### ISSUE TITLE
pose visualization function 

### ISSUE THREAD

**Issue by neixlo** [chensong1995/HybridPose#24]
I tried the visualization functions of coretrainer.py which are working pretty well! 
However, I also want to visualize the pose which is calculated in the regression module.

My code looks like this for drawing a simple coordinate system of the estimated pose with R_pred, t_pred into the image. Unfortunately it' not working.

```
def visualize_pose(camera_intrinsic, R, t, image):
    image_pred = image.copy()
    K = np.matrix([[camera_intrinsic['fu'], 0, camera_intrinsic['uc']],
                    [0, camera_intrinsic['fv'], camera_intrinsic['vc']],
                    [0, 0, 1]], dtype=np.float32)
    rotV, _ = cv2.Rodrigues(R)
    points = np.float32([[10, 0, 0], [0, 10, 0], [0, 0, 10], [0, 0, 0]]).reshape(-1, 3)
    axisPoints, _ = cv2.projectPoints(points, rotV, t, K, (0, 0, 0, 0))
    image_pred = cv2.line(image_pred, tuple(axisPoints[3].ravel()), tuple(axisPoints[0].ravel()), (255,0,0), 3)
    image_pred = cv2.line(image_pred, tuple(axisPoints[3].ravel()), tuple(axisPoints[1].ravel()), (0,255,0), 3)
    image_pred = cv2.line(image_pred, tuple(axisPoints[3].ravel()), tuple(axisPoints[2].ravel()), (0,0,255), 3)
    #show img
    cv2.imshow('Image_pose',image_pred)
    cv2.waitKey(0)
```
Do you have a snipped for me which you used for the image (Figure 1 (e), (f)) of the paper?

This would be a nice enhancement for this repository.

Thanks!

**Comment by chensong1995** [comment]
Hello neixlo,

Attached please find [the script](https://github.com/chensong1995/HybridPose/files/4541538/figure1.zip) I used to generate figure 1.  I performed the projection `p = K * (R * P + t)` using matrix multiplications in numpy. So perhaps you failed to use the OpenCV helper functions in an expected way. I am not completely sure about this though. I hope the script will help you debug your code.

You are more than welcome to create a pull request if you have a better visualization.

**Comment by neixlo** [comment]
This helped a lot, thanks!
