### ISSUE TITLE
About linemod model and occlusion linemod model 

### ISSUE THREAD

**Issue by firstdeep** [chensong1995/HybridPose#26]
Hello 

I'm going to use the "label.py' code you provided,
you used the cat/005.xyz model for the occlusion linemod dataset. 
Can you tell me which model you used for linemod dataset?
Did you run the symseg code using [linemod/original/dataset/cat/**cat.ply**] model?  

Also, I would appreciate it if you could share the "label.py" code written by linemod dataset.

**Comment by chensong1995** [comment]
Hello firstdeep,

Thanks for your questions!

- I used `mesh.ply` for labeling the Linemod dataset.
- Unfortunately, I am not able to provide the exact labeling script I used for the Linemod dataset. The original copy of the script is lost. However, the core logic is the same as the script I used for the Occlusion Linemod dataset.
- I ran the SymSeg code using `mesh.ply` model.

I hope this helps!

**Comment by firstdeep** [comment]
Thank you for your reply.

Lastly, I have one more question.
Did you proceed with normalization when executing symseg code using mesh.ply? 
Or did you just put it in the original mesh.ply?

Thank you 

Regrads.
David.

**Comment by chensong1995** [comment]
Can you explain what you mean exactly by "normalization"?

I do recall using some flips on the Linemod dataset, but I don't recall exactly how I did it. If you visualize the 2D projection and the result looks reasonable, it will most likely be good.

**Comment by firstdeep** [comment]
Oh i meant dividing the mesh.ply value by 1000.
Because the unit of translation is meter.

And did you proceed with Data augmentation before putting the data into the model?
such as, crop & Add noise 
I can't find that part(data augmentation) in your code.

Thank you 

David.

**Comment by chensong1995** [comment]
You can either do the unit conversion on the input or the output of SymSeg. I believe I did it on the output. I didn't do any additional data augmentation for training.

I hope this helps!

**Comment by firstdeep** [comment]
Thank you.
Your reply was very helpful.!

I hope the COVID-19 doesn't cause much damage to your lab.

Thank you.

David.
