### ISSUE TITLE
Is this a fair evaluation?

### ISSUE THREAD

**Issue by sh8** [chensong1995/HybridPose#31]

**Comment by chensong1995** [comment]
Hello Shun,

Thanks for your interest in our research! We use ADD-S as the main metric to quantitively evaluate the performance of HybridPose. ADD-S is widely used in the 6D pose estimation problem. The comparison of our approach and some important prior works is presented in Table 1 and 2 of the paper.

Best,
Chen

**Comment by hiyyg** [comment]
I found that the evaluation for both LM and LMO in your paper are not fair compared to other works. For LM, other works use 15% for training and 85% for testing. And for LMO, others use LM for training and the whole LMO for testing. However, you always use 80% for training and the rest 20% for testing. Thus I don't think the comparison to other works is fair.

**Comment by chensong1995** [comment]
To our knowledge, there is no standard training/testing split on Linemod.

**Comment by hiyyg** [comment]
Actually there is one standard train/test split, which is commonly used in ohter works.

**Comment by chensong1995** [comment]
We do recoginze that some of the works agree on a consistent split of the dataset. However, the split is not part of "Model Based Training, Detection and Pose Estimation of Texture-Less 3D Objects in Heavily Cluttered Scenes", which is the paper that proposed the dataset. The split is not given on the [dataset website](http://campar.in.tum.de/Main/StefanHinterstoisser), either.

Thanks again for your comment. Please stay tuned for our updated results.

**Comment by hiyyg** [comment]
It is not part of the original dataset paper. However, to my best of knowledge, in all baseline methods in your comparison table, they all use the same de facto split for reporting numbers.

**Comment by chensong1995** [comment]
Thanks for the information!

We now realize many of the baseline methods only use a limited set of examples for training, and rely on augmentation and synthesis to enrich the dataset. When doing our experiments, we realized that the performance of using single keypoints is similar to that of PVNet, which was where we started from. (You can run the code to double check this). So we took it for granted that this was the default case in prior works.

Still, we hope you can see the effects of hybrid representations from the ablation study, which compares different variants of HybridPose, without referring to the baseline approaches.

In the coming days, we will redo the experiments based on the conventional setting you suggested, and get back to you as soon as possible.

**Comment by hiyyg** [comment]
Yes. I do appreciate the ablation study of the effectness of the hybrid representation. However, the comparison numbers currently are totally meanfulless to me.

**Comment by chensong1995** [comment]
Please stay turned for our result updates.

**Comment by suruoxi** [comment]
Any updates?   @chensong1995

**Comment by chensong1995** [comment]
Hi suruoxi,

Thanks for your interest in our work. I am still actively working on re-evaluating this issue. Meanwhile, I just prepended a notice to the README of this repository, which reads:

_Important notice: We were informed by some readers that the training/testing split used in our experiment is inconsistent with baseline models. The comparison to baseline methods is therefore controversial. I am actively working on re-evaluating our approach. The updates will be posted to both this GitHub directory. At this point, I kindly request readers to focus on the general architecture of our method, and the relative strength of hybrid representations as demonstrated by the ablation study. I apologize for the inconvenience this may have caused._

Best,
Chen
