### ISSUE TITLE
Error about eigen

### ISSUE THREAD

**Issue by EasonEdison** [chensong1995/HybridPose#4]
I download eigen from http://eigen.tuxfamily.org/index.php?title=Main_Page
and copy HybridPose/lib/regressor/eigen

when I do make in HybridPose/lib/regressor, it show this:
```
Operation/pose_regression_parameter_search.cpp:365:31: error: ‘Eigen::VectorXd {aka class Eigen::Matrix<double, -1, 1>}’ has no member named ‘end’
       sort(temp.begin(), temp.end());
```

Maybe my eigen is error?

**Comment by chensong1995** [comment]
Hello EasonEdison,

Thank you for trying out our code! Can you try re-cloning the repository using `git clone --recurse-submodules git@github.com:chensong1995/HybridPose.git`? The `--recurse-submodules` option downloads Eigen to the correct location automatically. 

Let me know if the error persists.

**Comment by EasonEdison** [comment]
Thank you for your reply! When I asked this question, I am trying to download eigen at https://github.com/eigenteam/eigen-git-mirror
When I got your reply, it had been downloaded ,so I decided to test if this would work, but I spent many time to download dataset.
Today morning , all dataset had been downloaded ,and this eigen  work!
Thank you again! May I will ask you else question .
