### ISSUE TITLE
Could not restore session properly, check the load_dir

### ISSUE THREAD

**Issue by redredraccoon** [chensong1995/HybridPose#54]
您好，下载pre-trained weight后，想执行train的步骤，在train_core.py中已将--load_dir从None改成解压缩pre-trained weight的路径
`parser.add_argument('--load_dir', type=str, default='/home/raccoon/HybridPose/src/saved_weights/linemod/ape/checkpoints/0.001/199')#None`
取得GPU後，執行python train_core.py仍出現以下的error message
`(hybridpose) raccoon@nmsocadmin-734:~/HybridPose/src$ export LD_LIBRARY_PATH=/home/raccoon/HybridPose/lib/regressor`
`(hybridpose) raccoon@nmsocadmin-734:~/HybridPose/src$ python train_core.py`
`number of model parameters: 12959563`
`> /home/raccoon/HybridPose/lib/utils.py(36)load_session()`
`-> print('Could not restore session properly, check the load_dir')`
將/home/raccoon/HybridPose/lib/utils.py中的`def load_session(model, optim, args):`方程式做測試，發現載入權重的部分:
![image](https://user-images.githubusercontent.com/38128523/101153047-d5febf80-365e-11eb-930e-c7921eb961b5.png)
想請問到底是哪裡出錯了呢?
thanks

**Comment by chensong1995** [comment]
redredraccoon 你好，

感谢你对我们工作的关注！在第36行的断点处，如果把异常`e`的信息打印出来，会帮助我们判断问题具体出现在哪里。在pdb中，你可以用`(pdb) print e`来打印`e`的信息。

希望这有帮到你！

**Comment by redredraccoon** [comment]
您好，打印出來後，發現是cuda版本的問題，我這邊原本是cuda9.0，為符合此份code，應為cuda10.0。
謝謝您！
