### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by redredraccoon** [chensong1995/HybridPose#55]
您好，在使用pre-trained weight 做 train的步驟時，出現Segmentation fault的錯誤訊息(如下所示)
已使用cuda 10.0、並使用gpu來跑，想請問能否給提示呢? 謝謝

![image](https://user-images.githubusercontent.com/38128523/101350222-938ceb00-38c9-11eb-9a67-e9c0e048fe51.png)

**Comment by chensong1995** [comment]
你好 redredraccoon，

感谢你的提问！建议你试着用pdb单步跟踪一下错误具体出现在哪行。

**Comment by redredraccoon** [comment]
您好，我使用pdb後，發現HybridPose/trainers/coretrainer.py的572行出現error(如下圖所示)
![image](https://user-images.githubusercontent.com/38128523/101885666-64ca8980-3bd5-11eb-863a-393a1b5caa7e.png)
想請問您是使用gcc 4.9(或以上)的版本嗎? python版本是使用3.7.4嗎?
謝謝~

**Comment by chensong1995** [comment]
你可以单步跟到`vote_keypoints`这个函数里看一下吗？

**Comment by redredraccoon** [comment]
您好，
從HybridPose/src/train_core.py追蹤到HybridPose/trainers/coretrainer.py的vote_keypoints函數，
再追蹤到HybridPose/lib/ransac_voting_gpu_layer/ransac_voting_gpu.py，
發現是`cur_hyp_pts = ransac_voting.generate_hypothesis(direct, coords, idxs)`這行出現error message(如下圖所示)
進去ransac_voting_gpu.py查看後，並無查到`generate_hypothesis`的函式，
我認為此函式是源自"/home/ubuntu/HybridPose/lib/ransac_voting_gpu_layer/src/ransac_voting.cpp"，猜測無法順利啟用此函式的原因是gcc/g++版本與作者不同，所以想請問您是使用gcc 4.9(或以上)的版本嗎? python版本是使用3.7.4嗎? 謝謝
![image](https://user-images.githubusercontent.com/38128523/102017910-a65d5f00-3da4-11eb-9dc1-dcd7e133e0bb.png)
![image](https://user-images.githubusercontent.com/38128523/102017918-b37a4e00-3da4-11eb-85a7-a1ca7261d110.png)

**Comment by chensong1995** [comment]
```
(event) song@titan-1:/scratch/cluster/song/HybridPose/lib/ransac_voting_gpu_layer$ g++ --version
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(event) song@titan-1:/scratch/cluster/song/HybridPose/lib/ransac_voting_gpu_layer$ gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(event) song@titan-1:/scratch/cluster/song/HybridPose/lib/ransac_voting_gpu_layer$ /opt/cuda-10.0/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```

python 的版本是 3.7.4 。我猜测是 nvcc 没有配置好，你可以再试试。实在不行的话，可以发邮件给我，约个时间远程用 zoom 看一下。
