### ISSUE TITLE
About hyperparameters

### ISSUE THREAD

**Issue by chenjiale5** [chensong1995/HybridPose#59]
Hi!
This work is very interesting and I'm traning on my own dataset. however, I have some question about the hyperparameters pr_para and pi_para. I don't understand how it works and what role it plays in it. 
The symmetry of objects in our dataset is more complicated than in LINEMOD, like cups. It may have an infinite number of planes of symmetry, so we can not generate the sym_cor information.  In this situation, What can we do to make this code work?
Thanks!

**Comment by chensong1995** [comment]
Thanks for your question! For objects like cups, I would say the symmetric ambiguity problem is not unique to our symmetry correspondence representation. It creates a challenge for keypoints, edge vectors, and the dense correspondence map (used by some other works) as well. You may want to take a look at [this paper](http://www.cs.utoronto.ca/~ecorona/symmetry_pose_estimation/) and see if you can get some inspiration there.

I hope this helps!
