### ISSUE TITLE
Hybrid Pose on Custom Dataset

### ISSUE THREAD

**Issue by ishangupta3** [chensong1995/HybridPose#6]
Are there any pointers on the curation of a custom dataset which will match Hybrid Pose's data format?

**Comment by chensong1995** [comment]
Hello ishangupta3,

Thanks for trying out our code!

Our data format is actually pretty simple. I suggest you take a look at either [linemod.py](https://github.com/chensong1995/HybridPose/blob/master/lib/datasets/linemod.py) or [occlusion_linemod.py](https://github.com/chensong1995/HybridPose/blob/master/lib/datasets/occlusion_linemod.py).

To support a new custom dataset, you will need to create a `torch.utils.data.Dataset` class, whose `__getitem__()` returns a dictionary with [these keys](https://github.com/chensong1995/HybridPose/blob/master/lib/datasets/occlusion_linemod.py#L158). You then need to use this `Dataset` class in [train_core.py](https://github.com/chensong1995/HybridPose/blob/master/src/train_core.py). You should also make a choice on the covariance matrix [here](https://github.com/chensong1995/HybridPose/blob/master/trainers/coretrainer.py#L419). The two choices have more-or-less the same performance. You can try both of them.

I hope this helps.

**Comment by ishangupta3** [comment]
Thank you @chensong1995
