### ISSUE TITLE
Missing CAD models and custom annotations

### ISSUE THREAD

**Issue by lucasbrynte** [chensong1995/HybridPose#62]
Hi!

Thanks for the very interesting work!

I am trying to train HybridPose on LINEMOD according to the instructions, but receive an error for certain objects when training. It appears that some objects are missing a mesh.ply file (e.g. ./data/linemod/original_dataset/eggbox/mesh.ply).

I believe it is expected that the original LINEMOD data doesn't come with CAD models for all objects, but such models clearly seem to be expected. Could I be missing some pre-processing step? I've tried to follow the descriptions.

Thanks in advance!
Lucas

**Comment by chensong1995** [comment]
Hello Lucas,

Thanks for your interest in our work! I believe the original linemod dataset is missing mesh.ply on cam and eggbox (correct me if I am wrong). For these two objects, we simply convert the object.xyz file into the .ply format. 

Here is an example for cam:

![Screenshot from 2021-05-24 12-58-52](https://user-images.githubusercontent.com/21059441/119388406-dda73480-bc8f-11eb-9246-176bc36c9cd9.png)

On the left, we have object.xyz. On the right, we have mesh.ply. As you can see, the point coordinates match each other. This mesh.ply does not contain any edge information, neither does HybridPose use any edge information.

It is true that the occlusion linemod labels are given in a different coordinate frame than linemod. Please refer to [this line](https://github.com/chensong1995/HybridPose/blob/master/lib/datasets/occlusion_linemod.py#L73) for the conversion between the two coordinate frames.

I hope this helps!

**Comment by lucasbrynte** [comment]
Thank you Chen for the prompt reply, it's been really useful!

//Lucas
