### ISSUE TITLE
About the ablation study

### ISSUE THREAD

**Issue by JiChun-Wang** [chensong1995/HybridPose#65]
Hi, I have a question about the ablation study:
You have evaluated the performance of HybridPose under different predicted intermediate representations on the LineMod dataset. Now would you like to provide more further information on code implementation. How can I only use keypoints or keypoints and symmetry in initialization and refinement sub-modules?

**Comment by chensong1995** [comment]
Hello JiChun,

Thanks very much for your interest in our work! Please take a look at the exp_ablation branch of our repository. Around [this line](https://github.com/chensong1995/HybridPose/blob/exp_ablation/trainers/coretrainer.py#L457) we have the code for initialization and [this line](https://github.com/chensong1995/HybridPose/blob/exp_ablation/trainers/coretrainer.py#L503) for refinement.

I hope this helps! Let me know if you have further concerns.

**Comment by JiChun-Wang** [comment]
Thanks for your help.
