### ISSUE TITLE
Getting inference on ape saved_weights (from OneDrive)

### ISSUE THREAD

**Issue by monajalal** [chensong1995/HybridPose#79]
I am trying to get an inference on trained weights of ape however it tells me that I need the `blender_linemod`. Have you shared this data somewhere or are you able to share the link to downloading the data that is produced using `PVNet-Rendering`?

Also, why is there a need for synthetic data access in order to run the inference?

```
(hybridpose) mona@mona-ThinkStation-P7:~/HybridPose$ python src/train_core.py --load_dir saved_weights/linemod/ape/checkpoints/0.001/199 --object_name ape
Traceback (most recent call last):
  File "/home/mona/HybridPose/src/train_core.py", line 98, in <module>
    train_loader, test_loader, val_loader = setup_loaders(args)
  File "/home/mona/HybridPose/src/train_core.py", line 52, in setup_loaders
    blender_set = BlenderLinemodDataset(object_name=args.object_name, augment=True, occlude=False)
  File "/home/mona/HybridPose/lib/datasets/blender_linemod.py", line 40, in __init__
    self.length = len(list(filter(lambda x: x.endswith('jpg'), os.listdir(data_dir))))
FileNotFoundError: [Errno 2] No such file or directory: 'data/blender_linemod/ape'
```

https://github.com/chensong1995/HybridPose/issues/43#issuecomment-1586262802

**Comment by chensong1995** [comment]
Hello Mona,

Thanks for your interest in our work! To run the inference, you do not need to have the synthetic data. Feel free to remove the part that uses Blender data (i.e., [this line](https://github.com/chensong1995/HybridPose/blob/e9a4bb6115a9d3609cdf9b48691528aea3e17f20/src/train_core.py#L52), [this line](https://github.com/chensong1995/HybridPose/blob/e9a4bb6115a9d3609cdf9b48691528aea3e17f20/src/train_core.py#L58), and take out `blender_set` from [this line](https://github.com/chensong1995/HybridPose/blob/e9a4bb6115a9d3609cdf9b48691528aea3e17f20/src/train_core.py#L64C51-L64C62)). You do not need any of the training data to run the inference. If you are having trouble setting up other parts of the training data (e.g., `fuse_set`), please feel free to remove them as well.

I hope this helps! Let me know if you have further concerns.

**Comment by monajalal** [comment]
@chensong1995 thanks a lot for your response. Isn't fuse_set also dependent on the blender dataset?

I commented both blender_set and fuse_set and get the following error:
```
(hybridpose) mona@mona-ThinkStation-P7:~/HybridPose$ python src/train_core.py --load_dir saved_weights/linemod/ape/checkpoints/0.001/199 --object_name ape
number of model parameters: 12959563
Successfully loaded model from saved_weights/linemod/ape/checkpoints/0.001/199
Traceback (most recent call last):
  File "/home/mona/HybridPose/src/train_core.py", line 112, in <module>
    trainer.generate_data(val_loader)
  File "/home/mona/HybridPose/./trainers/coretrainer.py", line 548, in generate_data
    regressor = load_wrapper()
  File "/home/mona/HybridPose/lib/regressor/regressor.py", line 13, in load_wrapper
    regressor = CDLL('wrapper.so')
  File "/home/mona/anaconda3/envs/hybridpose/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: wrapper.so: cannot open shared object file: No such file or directory

```

**Comment by monajalal** [comment]
https://github.com/chensong1995/HybridPose/issues/22#issuecomment-862615326

**Comment by chensong1995** [comment]
Hi Mona,

Thanks for your follow-up! The error message suggests the program cannot find the file `wrapper.so`. Please follow README and [compile the pose regressor](https://github.com/chensong1995/HybridPose#compile-the-pose-regressor). I hope this helps! Let me know if you have further concerns.
