### ISSUE TITLE
Loading Pre - trained model without CUDA enabled?

### ISSUE THREAD

**Issue by ishangupta3** [chensong1995/HybridPose#8]
Hey, I am the very last step at src/train_core.py but I am running into the error below:

-> print('Could not restore session properly, check the load_dir')
(Pdb) 

Traceback (most recent call last):
  File "/home/ubuntu/HybridPose/lib/utils.py", line 25, in load_session
    **model.load_state_dict(torch.load(os.path.join(args.load_dir, 'model.pth')))**

  File "/home/ubuntu/anaconda3/envs/hybridpose/lib/python3.7/site-packages/torch/serialization.py", line 79, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: **Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.**

Can I load the model without CUDA being enabled? I am running it on an Ubuntu machine, deep learning instance, from aws currently where I have not set up CUDA.

**Comment by chensong1995** [comment]
Hello ishangupta3,

To load GPU-trained weights to a CPU device, please try [this](https://discuss.pytorch.org/t/on-a-cpu-device-how-to-load-checkpoint-saved-on-gpu-device/349).

I strongly recommend the use of GPU-based training and inference, though. It is very easy to set up on aws. Amazon has [Deep Learning AMI](https://aws.amazon.com/marketplace/pp/Amazon-Web-Services-AWS-Deep-Learning-AMI-Ubuntu-1/B07Y43P7X5) that pre-installs the CUDA environment.

**Comment by ishangupta3** [comment]
Thanks for the response,

I have the Deep Learning AMI with the pre installed CUDA environment; currently I am in the conda environment that I created using the instructions on the repo. How can I install the pre installed CUDA environment while being in the hybrid pose conda environment to get it up and running. 

The reason is that I would like to avoid starting from scratch in terms of downloading the dependencies and data.

**Comment by ishangupta3** [comment]
I am looking online, and it seems that I have to install a driver:

Will these commands be enough to run within the hybrid pose conda environment:

wget http://us.download.nvidia.com/tesla/375.66/nvidia-diag-driver-local-repo-ubuntu1604_375.66-1_amd64.deb
dpkg -i nvidia-diag-driver-local-repo-ubuntu1604_375.66-1_amd64.deb
sudo apt-get update
sudo apt-get -y install cuda-drivers
sudo apt-get update && sudo apt-get -y upgrade

**Comment by chensong1995** [comment]
> I am looking online, and it seems that I have to install a driver:
> 
> Will these commands be enough to run within the hybrid pose conda environment:
> 
> wget http://us.download.nvidia.com/tesla/375.66/nvidia-diag-driver-local-repo-ubuntu1604_375.66-1_amd64.deb
> dpkg -i nvidia-diag-driver-local-repo-ubuntu1604_375.66-1_amd64.deb
> sudo apt-get update
> sudo apt-get -y install cuda-drivers
> sudo apt-get update && sudo apt-get -y upgrade

I am glad to hear that you have figured it out.

**Comment by ishangupta3** [comment]
> > I am looking online, and it seems that I have to install a driver:
> > Will these commands be enough to run within the hybrid pose conda environment:
> > wget http://us.download.nvidia.com/tesla/375.66/nvidia-diag-driver-local-repo-ubuntu1604_375.66-1_amd64.deb
> > dpkg -i nvidia-diag-driver-local-repo-ubuntu1604_375.66-1_amd64.deb
> > sudo apt-get update
> > sudo apt-get -y install cuda-drivers
> > sudo apt-get update && sudo apt-get -y upgrade
> 
> I am glad to hear that you have figured it out.

@chensong1995 it did not work, do you have personal experience running an AWS ubuntu instance and correctly installing the CUDA libraries to work with Pytorch?

**Comment by chensong1995** [comment]
I have only limited experience with AWS. In retrospect, I do not think I ever installed CUDA myself on the EC2 instances. If I remember correctly, CUDA was out-of-the-box and came together with the deep learning AMI.

I am not an expert in AWS, though. I would recommend you to contact Amazon customer service for questions specific to their products.

I hope this helps.

**Comment by ishangupta3** [comment]
Thanks for your help @chensong1995.
