### ISSUE TITLE
how to read into and make sense of data inside test_set_ape.npy

### ISSUE THREAD

**Issue by monajalal** [chensong1995/HybridPose#82]
After running this command:
` LD_LIBRARY_PATH=lib/regressor:$LD_LIBRARY_PATH python src/train_core.py`

I get this file as output:
`/home/mona/HybridPose/output/linemod/test_set_ape.npy`

and I am not sure how to read into this result to judge if using the pretrained weights is doing a good job or not. Is there an easier way to judge this like a single accuracy number?

**Comment by monajalal** [comment]
actually nvm I think something was wrong with using the pretrained weights saved file since evaluate is giving 0 for ADD-S score
```

(hybridpose) mona@mona-ThinkStation-P7:~/HybridPose$ python src/evaluate.py
ADD(-S) score of initial prediction is: 0.0
ADD(-S) score of final prediction is: 0.0
```


```
    # parser.add_argument('--prediction_file', type=str, default='output/occlusion_linemod/test_set_ape_40.npy')
    parser.add_argument('--prediction_file', type=str, default='/home/mona/HybridPose/output/linemod/test_set_ape.npy')
```

**Comment by chensong1995** [comment]
Hi Mona,

Thanks for the question! My suggestion is to inspect the values of the `record` object [here](https://github.com/chensong1995/HybridPose/blob/e9a4bb6115a9d3609cdf9b48691528aea3e17f20/src/evaluate.py#L51). The zero accuracy may be related to the other issue you raised #81 too.

I hope this helps! Let me know if you have further concerns.
