### ISSUE TITLE
Using the QR codes using training, do they need to be present during inference?

### ISSUE THREAD

**Issue by ishangupta3** [chensong1995/HybridPose#9]
The aruco markers (QR codes )help provide the Rt matrix. If they are used in the training data, do they need to be also present during inference?

What would be the best way to acquire the Rt (ground truth pose matrix) with/without the qr codes in your personal opinion ?

**Comment by chensong1995** [comment]
Hello ishangupta3,

Thanks for your questions!

The pipeline of HybridPose does not assume the existence of aruco markers in the background. However, it is indeed the case that both the datasets we experimented on contain those QR codes.

When the regression network is trained on images with a certain type of background, and tested on images with another type of background, there will be a generalization issue. To compensate this, you may try using some synthesized training examples, like what the authors in [PVNet](https://github.com/zju3dv/pvnet) did.

I am not an expert in dataset labeling. However, if I were to create a brand-new 6DoF object pose dataset, I would first look into planting some small (ideally invisible) electronic markers into the object. These markers should be able to somehow use radio waves to locate their 3D positions. The 3D positions will allow me to acquire the ground-truth object pose.

I hope this helps.

**Comment by ishangupta3** [comment]
Thank you @chensong1995 .
